#!/usr/bin/env python3
import os
import random
import signal
import sys

from base.config import (
    RAINB0W_BACKUP_DIR,
    RAINB0W_CONFIG_FILE,
    RAINB0W_HOME_DIR,
    RAINB0W_USERS_FILE,
    SINGBOX_CONFIG_FILE,
    WARP_CONF_FILE,
)
from proxy.hysteria import configure_hysteria, prompt_hysteria_sni
from proxy.reality import configure_reality, prompt_reality_destination_server
from proxy.warp import configure_warp
from user.user_manager import (
    add_user_to_list,
    add_user_to_proxies,
    create_new_user,
    get_users,
    prompt_username,
)
from utils.helper import (
    copy_file,
    gen_random_string,
    load_toml,
    progress_indicator,
    remove_dir,
    save_toml,
)
from utils.os_utils import run_system_cmd


def apply_config():
    rainb0w_config = load_toml(RAINB0W_CONFIG_FILE)
    configure_reality(
        rainb0w_config["REALITY"],
        SINGBOX_CONFIG_FILE,
    )
    configure_hysteria(
        rainb0w_config["HYSTERIA"],
        SINGBOX_CONFIG_FILE,
    )
    configure_warp(SINGBOX_CONFIG_FILE, WARP_CONF_FILE)

    # Add users from the rainb0w_users.toml into proxies
    rainb0w_users = get_users(RAINB0W_USERS_FILE)
    for user in rainb0w_users:
        add_user_to_proxies(user, SINGBOX_CONFIG_FILE)

    exit(0)


def restore_config():
    print("Restoring your configuration and users...")
    if os.path.exists(RAINB0W_BACKUP_DIR):
        copy_file(
            f"{RAINB0W_BACKUP_DIR}/{os.path.basename(RAINB0W_CONFIG_FILE)}",
            RAINB0W_CONFIG_FILE,
        )
        copy_file(
            f"{RAINB0W_BACKUP_DIR}/{os.path.basename(RAINB0W_USERS_FILE)}",
            RAINB0W_USERS_FILE,
        )
        apply_config()
    else:
        print(f"ERROR: No data found at: {RAINB0W_BACKUP_DIR}")
        print(
            f"Please copy your backup files to \
                    '{RAINB0W_BACKUP_DIR}' and run the installer again!"
        )
        exit(1)


def configure():
    rainb0w_config = load_toml(RAINB0W_CONFIG_FILE)
    rainb0w_users = get_users(RAINB0W_USERS_FILE)

    # Configure REALITY
    # Public and private keys will be generated by deploy.sh
    rainb0w_config["REALITY"]["SNI"], rainb0w_config["REALITY"]["PORT"] = (
        prompt_reality_destination_server()
    )
    rainb0w_config["REALITY"]["SHORT_ID"] = "".join(
        random.choice("0123456789abcdef") for _ in range(16)
    )

    # Configure Hysteria
    rainb0w_config["HYSTERIA"]["SNI"] = prompt_hysteria_sni()
    rainb0w_config["HYSTERIA"]["OBFS"] = gen_random_string(random.randint(8, 12))

    # Configure first user
    username = prompt_username()
    user_info = create_new_user(username)
    add_user_to_list(user_info, RAINB0W_USERS_FILE)

    save_toml(rainb0w_config, RAINB0W_CONFIG_FILE)

    apply_config()


def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == "Install":
            configure()
        elif sys.argv[1] == "Restore":
            restore_config()
        else:
            print("Unknown installation type passed! Exiting!")
            exit(1)
    else:
        print("Not enough args passed! Exiting!")
        exit(1)


def signal_handler(sig, frame):
    remove_dir(RAINB0W_HOME_DIR)
    print("\nOkay! Exiting!")
    sys.exit(1)


if __name__ == "__main__":
    # Enable bailing out!
    signal.signal(signal.SIGINT, signal_handler)
    main()
